export { default as InfoStep } from './InfoStep'
export { default as UploadPhotoStep } from './UploadPhotoStep'
export { default as AnalysisResultStep } from './AnalysisResultStep'
export { default as RegisterResultStep } from './RegisterResultStep'
export { default as SelectOptions } from './SelectOptions'
